---
# Source: example-todo-model-service-preview/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-todo-model-service-pr-70-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/example-todo-model-service.git
    targetRevision: renovate/node-18.x
    helm:
      version: v3
      values: |
        image:
          tag: pr-70-dde3eb8b7a13ee88c70ad42fdfc4ff52f18ba7dc
        env:
          EXAMPLE_HASURA_PROJECTIONS_URL: http://example-hasura-projections-service.example-prod-env.svc.cluster.local
          TODO_EVENTS_BROKER_URL: "http://broker-ingress.knative-eventing.svc.cluster.local/example-prod-env/todo-events"
  destination:
    namespace: example-todo-model-service-pr-70-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
# Source: example-todo-model-service-preview/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-todo-model-service-pr-70-preview-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.5.3
    helm:
      version: v3
  destination:
    namespace: example-todo-model-service-pr-70-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: example-todo-model-service-preview/templates/sourced-db.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-todo-model-service-pr-70-preview-sourced-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: example-preview-envs
  source:
    path: charts/sourced-db
    repoURL: https://github.com/cloudnativeentrepreneur/sourced-db.git
    targetRevision: HEAD
    helm:
      version: v3
  destination:
    namespace: example-todo-model-service-pr-70-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
