---
# Source: example-dlq-service/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-dlq-service-pr-60-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/example-dlq-service.git
    targetRevision: renovate/prettier-2.x
    helm:
      version: v3
      values: |
        image:
          tag: pr-60-43976ed8a7e73ef5bbba25b8aed12577d5397648
  destination:
    namespace: example-dlq-service-pr-60-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: example-dlq-service/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-dlq-service-pr-60-preview-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.5.3
    helm:
      version: v3
  destination:
    namespace: example-dlq-service-pr-60-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
